# Generated by Django 2.0.6 on 2018-07-11 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added_list', 'added_list'), ('update_list', 'update_list'), ('archived_list', 'archived_list'), ('added_card', 'added_card'), ('updated_card_title', 'updated_card_title'), ('updated_card_description', 'updated_card_description'), ('add_comment', 'add_comment'), ('deleted_comment', 'deleted_comment'), ('transferred_card', 'transferred_card'), ('assign_member', 'assign_member')], max_length=25)),
                ('object_id', models.PositiveIntegerField()),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
