# Generated by Django 3.2.8 on 2022-03-05 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20220305_1114'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(max_length=25),
        ),
    ]
