# Generated by Django 3.2.8 on 2022-05-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_card_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
    ]
