# Generated by Django 3.2.8 on 2021-10-27 22:56

from django.db import migrations
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', register.models.CustomUserManager()),
            ],
        ),
    ]
