# Generated by Django 3.2.8 on 2021-11-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timeline_settings_category_show',
            field=models.CharField(choices=[('show', '表示'), ('none', '非表示')], default='show', max_length=30),
        ),
    ]
