# Generated by Django 3.2.8 on 2022-02-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_timeline_settings_category_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar', verbose_name='プロフィール画像'),
        ),
    ]
