# Generated by Django 3.2.8 on 2021-11-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='white', max_length=30),
        ),
    ]
