# Generated by Django 3.2.8 on 2022-02-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_timelinemodel_members'),
        ('register', '0004_user_favorite_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_project',
            field=models.ManyToManyField(blank=True, related_name='favorite_project', to='app.TaskProjectModel', verbose_name='お気に入りのプロジェクト'),
        ),
    ]
