# Generated by Django 3.2.8 on 2023-01-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_user_favorite_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='done_task_calendar_show',
            field=models.BooleanField(default=False),
        ),
    ]
