# Generated by Django 3.2.8 on 2021-11-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('ホワイト', 'white'), ('dark', 'dark')], default='white', max_length=30),
        ),
    ]
