# Generated by Django 3.2.8 on 2021-11-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('white', 'ホワイト'), ('dark', 'ダーク')], default='white', max_length=30),
        ),
    ]
