# Generated by Django 3.2.8 on 2021-11-18 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時間')),
                ('category', models.CharField(blank=True, choices=[('生活', '生活'), ('仕事', '仕事'), ('家族', '家族')], default='未分類', max_length=30, verbose_name='カテゴリ')),
                ('status', models.CharField(blank=True, choices=[('過ぎています。', '過ぎています。'), ('完了', '完了'), ('対応中', '対応中'), ('未対応', '未対応')], default='未分類', max_length=30, verbose_name='ステータス')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_user_routine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
