# Generated by Django 3.2.8 on 2021-11-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_routinemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinemodel',
            name='category',
            field=models.CharField(blank=True, choices=[('インボックス', 'インボックス'), ('生活', '生活'), ('仕事', '仕事'), ('家族', '家族')], default='インボックス', max_length=30, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='routinemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('過ぎています。', '過ぎています。'), ('完了', '完了'), ('対応中', '対応中'), ('未対応', '未対応')], default='未対応', max_length=30, verbose_name='ステータス'),
        ),
    ]
