# Generated by Django 3.2.8 on 2021-12-02 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_routinemodel_taskprojectmodel_timelinemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskproject_model', to='app.taskprojectmodel'),
        ),
        migrations.AlterField(
            model_name='taskprojectmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タスクプロジェクト名'),
        ),
        migrations.CreateModel(
            name='TaskSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateData', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=50, verbose_name='タスクセクション名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_user_task_section', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_section_taskproject_model', to='app.taskprojectmodel')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasksection_model', to='app.tasksectionmodel'),
        ),
    ]
