# Generated by Django 3.2.8 on 2021-11-21 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_timelinemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinemodel',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_model', to='app.timelinemodel'),
        ),
    ]
