# Generated by Django 3.2.8 on 2022-01-08 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20211202_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprojectmodel',
            name='members',
            field=models.ManyToManyField(related_name='relate_members_task_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
