# Generated by Django 3.2.8 on 2022-01-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220108_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinemodel',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
