# Generated by Django 3.2.8 on 2022-02-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_timelinemodel_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_task_to_project', to='app.taskprojectmodel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_task_to_section', to='app.tasksectionmodel'),
        ),
    ]
