# Generated by Django 3.2.8 on 2022-02-20 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20220218_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinemodel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='relate_members_timeline', to=settings.AUTH_USER_MODEL),
        ),
    ]
